# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

{
'target_defaults': {
  'include_dirs': [
	'Authentication',
	'Core',
	'Categories',
	'Utilities',
	'Vendor/CocoaAsyncSocket',
	'Vendor/CocoaLumberjack',
	'Vendor/KissXml',
	"$(SDKROOT)/usr/include/libxml2",
  ],
  'xcode_settings': {
	'CLANG_ENABLE_OBJC_ARC': 'YES',
  },
},
'targets': [
	{
	  'target_name': 'xmppframework_auth',
	  'type': 'static_library',
	  'sources': [
		'Authentication/Anonymous/XMPPAnonymousAuthentication.h',
		'Authentication/Anonymous/XMPPAnonymousAuthentication.m',
		'Authentication/Deprecated-Digest/XMPPDeprecatedDigestAuthentication.h',
		'Authentication/Deprecated-Digest/XMPPDeprecatedDigestAuthentication.m',
		'Authentication/Deprecated-Plain/XMPPDeprecatedPlainAuthentication.h',
		'Authentication/Deprecated-Plain/XMPPDeprecatedPlainAuthentication.m',
		'Authentication/Digest-MD5/XMPPDigestMD5Authentication.h',
		'Authentication/Digest-MD5/XMPPDigestMD5Authentication.m',
		'Authentication/Plain/XMPPPlainAuthentication.h',
		'Authentication/Plain/XMPPPlainAuthentication.m',
		'Authentication/X-Facebook-Platform/XMPPXFacebookPlatformAuthentication.h',
		'Authentication/X-Facebook-Platform/XMPPXFacebookPlatformAuthentication.m',
		'Authentication/XMPPSASLAuthentication.h',
	  ],
	},
	{
	  'target_name': 'xmppframework_cocoaasyncsocket',
	  'type': 'static_library',
	  'sources': [
		'Vendor/CocoaAsyncSocket/GCDAsyncSocket.h',
		'Vendor/CocoaAsyncSocket/GCDAsyncSocket.m',
	  ],
	},
	{
	  'target_name': 'xmppframework_core',
	  'type': 'static_library',
	  'sources': [
		  'XMPPFramework.h'
		  'Core/XMPP.h',
		  'Core/XMPPElement.h',
		  'Core/XMPPElement.m',
		  'Core/XMPPInternal.h',
		  'Core/XMPPIQ.h',
		  'Core/XMPPIQ.m',
		  'Core/XMPPJID.h',
		  'Core/XMPPJID.m',
		  'Core/XMPPLogging.h',
		  'Core/XMPPMessage.h',
		  'Core/XMPPMessage.m',
		  'Core/XMPPModule.h',
		  'Core/XMPPModule.m',
		  'Core/XMPPParser.h',
		  'Core/XMPPParser.m',
		  'Core/XMPPPresence.h',
		  'Core/XMPPPresence.m',
		  'Core/XMPPStream.h',
		  'Core/XMPPStream.m',
	  ],
	  'dependencies': [
		'xmppframework_kiss_xml',
	  ],
  	  'include_dirs': [
		'Vendor/libidn',
		'Vendor/KissXML/Private',
	  ],
	},
	{
	  'target_name': 'xmppframework_categories',
	  'type': 'static_library',
	  'sources': [
		'Categories/NSData+XMPP.h',
		'Categories/NSData+XMPP.m',
		'Categories/NSNumber+XMPP.h',
		'Categories/NSNumber+XMPP.m',
		'Categories/NSXMLElement+XMPP.h',
		'Categories/NSXMLElement+XMPP.m',
	  ],
	},
	{
	  'target_name': 'xmppframework_kiss_xml',
	  'type': 'static_library',
	  'sources': [
		'Vendor/KissXML/Categories/NSString+DDXML.h',
		'Vendor/KissXML/Categories/NSString+DDXML.m',
		'Vendor/KissXML/DDXML.h',
		'Vendor/KissXML/DDXMLDocument.h',
		'Vendor/KissXML/DDXMLDocument.m',
		'Vendor/KissXML/DDXMLElement.h',
		'Vendor/KissXML/DDXMLElement.m',
		'Vendor/KissXML/DDXMLNode.h',
		'Vendor/KissXML/DDXMLNode.m',
		'Vendor/KissXML/Private/DDXMLPrivate.h',
	  ],
  	  'include_dirs': [
		'Vendor/KissXML/Private/',
		'Vendor/KissXML/Categories/',
	  ],
	},
	{
	  'target_name': 'xmppframework_cocoaalumberjack',
	  'type': 'static_library',
	  'sources': [
		'Vendor/CocoaLumberjack/DDAbstractDatabaseLogger.h',
		'Vendor/CocoaLumberjack/DDAbstractDatabaseLogger.m',
		'Vendor/CocoaLumberjack/DDASLLogger.h',
		'Vendor/CocoaLumberjack/DDASLLogger.m',
		'Vendor/CocoaLumberjack/DDFileLogger.h',
		'Vendor/CocoaLumberjack/DDFileLogger.m',
		'Vendor/CocoaLumberjack/DDLog.h',
		'Vendor/CocoaLumberjack/DDLog.m',
		'Vendor/CocoaLumberjack/DDTTYLogger.h',
		'Vendor/CocoaLumberjack/DDTTYLogger.m',
		'Vendor/CocoaLumberjack/Extensions/ContextFilterLogFormatter.h',
		'Vendor/CocoaLumberjack/Extensions/ContextFilterLogFormatter.m',
		'Vendor/CocoaLumberjack/Extensions/DispatchQueueLogFormatter.h',
		'Vendor/CocoaLumberjack/Extensions/DispatchQueueLogFormatter.m',
	  ],
	},
	{
	  'target_name': 'xmppframework_extensions',
	  'type': 'static_library',
	  'sources': [
		'Extensions/BandwidthMonitor/XMPPBandwidthMonitor.h',
		'Extensions/BandwidthMonitor/XMPPBandwidthMonitor.m',
		'Extensions/CoreDataStorage/XMPPCoreDataStorage.h',
		'Extensions/CoreDataStorage/XMPPCoreDataStorage.m',
		'Extensions/CoreDataStorage/XMPPCoreDataStorageProtected.h',
		'Extensions/ProcessOne/XMPPProcessOne.h',
		'Extensions/ProcessOne/XMPPProcessOne.m',
		'Extensions/Reconnect/XMPPReconnect.h',
		'Extensions/Reconnect/XMPPReconnect.m',
		'Extensions/Roster/CoreDataStorage/XMPPGroupCoreDataStorageObject.h',
		'Extensions/Roster/CoreDataStorage/XMPPGroupCoreDataStorageObject.m',
		'Extensions/Roster/CoreDataStorage/XMPPResourceCoreDataStorageObject.h',
		'Extensions/Roster/CoreDataStorage/XMPPResourceCoreDataStorageObject.m',
		'Extensions/Roster/CoreDataStorage/XMPPRosterCoreDataStorage.h',
		'Extensions/Roster/CoreDataStorage/XMPPRosterCoreDataStorage.m',
		'Extensions/Roster/CoreDataStorage/XMPPUserCoreDataStorageObject.h',
		'Extensions/Roster/CoreDataStorage/XMPPUserCoreDataStorageObject.m',
		'Extensions/Roster/MemoryStorage/XMPPResourceMemoryStorageObject.h',
		'Extensions/Roster/MemoryStorage/XMPPResourceMemoryStorageObject.m',
		'Extensions/Roster/MemoryStorage/XMPPRosterMemoryStorage.h',
		'Extensions/Roster/MemoryStorage/XMPPRosterMemoryStorage.m',
		'Extensions/Roster/MemoryStorage/XMPPRosterMemoryStoragePrivate.h',
		'Extensions/Roster/MemoryStorage/XMPPUserMemoryStorageObject.h',
		'Extensions/Roster/MemoryStorage/XMPPUserMemoryStorageObject.m',
		'Extensions/Roster/XMPPResource.h',
		'Extensions/Roster/XMPPRoster.h',
		'Extensions/Roster/XMPPRoster.m',
		'Extensions/Roster/XMPPRosterPrivate.h',
		'Extensions/Roster/XMPPUser.h',
		'Extensions/XEP-0009/XMPPIQ+JabberRPC.h',
		'Extensions/XEP-0009/XMPPIQ+JabberRPC.m',
		'Extensions/XEP-0009/XMPPIQ+JabberRPCResonse.h',
		'Extensions/XEP-0009/XMPPIQ+JabberRPCResonse.m',
		'Extensions/XEP-0009/XMPPJabberRPCModule.h',
		'Extensions/XEP-0009/XMPPJabberRPCModule.m',
		'Extensions/XEP-0016/XMPPPrivacy.h',
		'Extensions/XEP-0016/XMPPPrivacy.m',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoomCoreDataStorage.h',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoomCoreDataStorage.m',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoomMessageCoreDataStorageObject.h',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoomMessageCoreDataStorageObject.m',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoomOccupantCoreDataStorageObject.h',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoomOccupantCoreDataStorageObject.m',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomHybridStorage.h',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomHybridStorage.m',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomHybridStorageProtected.h',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomMessageHybridCoreDataStorageObject.h',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomMessageHybridCoreDataStorageObject.m',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomOccupantHybridMemoryStorageObject.h',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomOccupantHybridMemoryStorageObject.m',
		'Extensions/XEP-0045/MemoryStorage/XMPPRoomMemoryStorage.h',
		'Extensions/XEP-0045/MemoryStorage/XMPPRoomMemoryStorage.m',
		'Extensions/XEP-0045/MemoryStorage/XMPPRoomMessageMemoryStorageObject.h',
		'Extensions/XEP-0045/MemoryStorage/XMPPRoomMessageMemoryStorageObject.m',
		'Extensions/XEP-0045/MemoryStorage/XMPPRoomOccupantMemoryStorageObject.h',
		'Extensions/XEP-0045/MemoryStorage/XMPPRoomOccupantMemoryStorageObject.m',
		'Extensions/XEP-0045/XMPPMessage+XEP0045.h',
		'Extensions/XEP-0045/XMPPMessage+XEP0045.m',
		'Extensions/XEP-0045/XMPPMUC.h',
		'Extensions/XEP-0045/XMPPMUC.m',
		'Extensions/XEP-0045/XMPPRoom.h',
		'Extensions/XEP-0045/XMPPRoom.m',
		'Extensions/XEP-0045/XMPPRoomMessage.h',
		'Extensions/XEP-0045/XMPPRoomOccupant.h',
		'Extensions/XEP-0045/XMPPRoomPrivate.h',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardAvatarCoreDataStorageObject.h',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardAvatarCoreDataStorageObject.m',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardCoreDataStorage.h',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardCoreDataStorage.m',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardCoreDataStorageObject.h',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardCoreDataStorageObject.m',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardTempCoreDataStorageObject.h',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCardTempCoreDataStorageObject.m',
		'Extensions/XEP-0054/XMPPvCardTemp.h',
		'Extensions/XEP-0054/XMPPvCardTemp.m',
		'Extensions/XEP-0054/XMPPvCardTempAdr.h',
		'Extensions/XEP-0054/XMPPvCardTempAdr.m',
		'Extensions/XEP-0054/XMPPvCardTempAdrTypes.h',
		'Extensions/XEP-0054/XMPPvCardTempAdrTypes.m',
		'Extensions/XEP-0054/XMPPvCardTempBase.h',
		'Extensions/XEP-0054/XMPPvCardTempBase.m',
		'Extensions/XEP-0054/XMPPvCardTempEmail.h',
		'Extensions/XEP-0054/XMPPvCardTempEmail.m',
		'Extensions/XEP-0054/XMPPvCardTempLabel.h',
		'Extensions/XEP-0054/XMPPvCardTempLabel.m',
		'Extensions/XEP-0054/XMPPvCardTempModule.h',
		'Extensions/XEP-0054/XMPPvCardTempModule.m',
		'Extensions/XEP-0054/XMPPvCardTempTel.h',
		'Extensions/XEP-0054/XMPPvCardTempTel.m',
		'Extensions/XEP-0060/XMPPPubSub.h',
		'Extensions/XEP-0060/XMPPPubSub.m',
		'Extensions/XEP-0065/TURNSocket.h',
		'Extensions/XEP-0065/TURNSocket.m',
		'Extensions/XEP-0082/NSDate+XMPPDateTimeProfiles.h',
		'Extensions/XEP-0082/NSDate+XMPPDateTimeProfiles.m',
		'Extensions/XEP-0082/XMPPDateTimeProfiles.h',
		'Extensions/XEP-0082/XMPPDateTimeProfiles.m',
		'Extensions/XEP-0085/XMPPMessage+XEP_0085.h',
		'Extensions/XEP-0085/XMPPMessage+XEP_0085.m',
		'Extensions/XEP-0100/XMPPTransports.h',
		'Extensions/XEP-0100/XMPPTransports.m',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapabilitiesCoreDataStorage.h',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapabilitiesCoreDataStorage.m',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapsCoreDataStorageObject.h',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapsCoreDataStorageObject.m',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapsResourceCoreDataStorageObject.h',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapsResourceCoreDataStorageObject.m',
		'Extensions/XEP-0115/XMPPCapabilities.h',
		'Extensions/XEP-0115/XMPPCapabilities.m',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchiving_Contact_CoreDataObject.h',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchiving_Contact_CoreDataObject.m',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchiving_Message_CoreDataObject.h',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchiving_Message_CoreDataObject.m',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchivingCoreDataStorage.h',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchivingCoreDataStorage.m',
		'Extensions/XEP-0136/XMPPMessageArchiving.h',
		'Extensions/XEP-0136/XMPPMessageArchiving.m',
		'Extensions/XEP-0153/XMPPvCardAvatarModule.h',
		'Extensions/XEP-0153/XMPPvCardAvatarModule.m',
		'Extensions/XEP-0184/XMPPMessage+XEP_0184.h',
		'Extensions/XEP-0184/XMPPMessage+XEP_0184.m',
		'Extensions/XEP-0199/XMPPAutoPing.h',
		'Extensions/XEP-0199/XMPPAutoPing.m',
		'Extensions/XEP-0199/XMPPPing.h',
		'Extensions/XEP-0199/XMPPPing.m',
		'Extensions/XEP-0202/XMPPAutoTime.h',
		'Extensions/XEP-0202/XMPPAutoTime.m',
		'Extensions/XEP-0202/XMPPTime.h',
		'Extensions/XEP-0202/XMPPTime.m',
		'Extensions/XEP-0203/XMPPElement+Delay.h',
		'Extensions/XEP-0203/XMPPElement+Delay.m',
		'Extensions/XEP-0224/XMPPAttentionModule.h',
		'Extensions/XEP-0224/XMPPAttentionModule.m',
		'Extensions/XEP-0224/XMPPMessage+XEP_0224.h',
		'Extensions/XEP-0224/XMPPMessage+XEP_0224.m',
		'Extensions/Roster/CoreDataStorage/XMPPRoster.xcdatamodel',
		'Extensions/XEP-0045/CoreDataStorage/XMPPRoom.xcdatamodeld/XMPPRoom.xcdatamodel',
		'Extensions/XEP-0045/HybridStorage/XMPPRoomHybrid.xcdatamodeld/XMPPRoomHybrid.xcdatamodel',
		'Extensions/XEP-0054/CoreDataStorage/XMPPvCard.xcdatamodeld/XMPPvCard.xcdatamodel',
		'Extensions/XEP-0115/CoreDataStorage/XMPPCapabilities.xcdatamodel',
		'Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchiving.xcdatamodeld/XMPPMessageArchiving.xcdatamodel',
	  ],
  	  'include_dirs': [
	  	'.',
	  	'Extensions/Roster',
		'Extensions/Roster/CoreDataStorage',
		'Extensions/CoreDataStorage',
		'Extensions/XEP-0045',
		'Extensions/XEP-0045/CoreDataStorage',
		'Extensions/XEP-0054',
		'Extensions/XEP-0054/CoreDataStorage',
		'Extensions/XEP-0082',
		'Extensions/XEP-0085',
		'Extensions/XEP-0115',
		'Extensions/XEP-0115/CoreDataStorage',
		'Extensions/XEP-0136',
		'Extensions/XEP-0153',
		'Extensions/XEP-0203',
		'Extensions/Reconnect',
	  ],
	},
	{
	  'target_name': 'xmppframework_utilities',
	  'type': 'static_library',
	  'sources': [
		'Utilities/DDList.h',
		'Utilities/DDList.m',
		'Utilities/GCDMulticastDelegate.h',
		'Utilities/GCDMulticastDelegate.m',
		'Utilities/LibIDN.h',
		'Utilities/LibIDN.m',
		'Utilities/RFImageToDataTransformer.h',
		'Utilities/RFImageToDataTransformer.m',
		'Utilities/XMPPIDTracker.h',
		'Utilities/XMPPIDTracker.m',
		'Utilities/XMPPSRVResolver.h',
		'Utilities/XMPPSRVResolver.m',
	  ],
	  'dependencies': [
		'xmppframework_libidn',
	  ],
  	  'include_dirs': [
		'Vendor/libidn/',
	  ],
	},
	{
	  'target_name': 'xmppframework_libidn',
	  'type': 'none',
      'link_settings': {
        'libraries': [
          'Vendor/libidn/libidn.a',
        ],
      },
	  'sources': [
		'Vendor/libidn/stringprep.h'
	  ],
	},
	{
	  'target_name': 'xmppframework_all',
	  'type': 'none',
	  'dependencies': [
		'xmppframework_auth',
		'xmppframework_cocoaasyncsocket',
		'xmppframework_core',
		'xmppframework_categories',
		'xmppframework_cocoaalumberjack',
		'xmppframework_extensions',
		'xmppframework_utilities',
	  ],
	  'xcode_settings': {
		'OTHER_LDFLAGS': [
			'-framework CoreData',
			'-framework UIKit',
			'-lxml2',
		],
	  },
	},
  ],
}
